version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs"]
  style_guide = "google"
  dialect = "typescript"

[[transformers]]
name = "prettier"
enabled = true
